# Generated by Django 3.0.6 on 2020-05-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='Kuks',
            new_name='kuks',
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
