# Generated by Django 3.0.6 on 2020-05-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20200506_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
