# Generated by Django 3.0.6 on 2020-05-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20200506_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.IntegerField(help_text='MMDDYYYY', verbose_name='Date'),
        ),
    ]
